services:
  app:
    build: .
    image: art-nodes:latest
    container_name: art-nodes
    # Map host -> container using env vars. Defaults: HOST_PORT=3001, PORT=3000
    ports:
      - "${HOST_PORT:-3001}:${PORT:-3000}"
    environment:
      - NODE_ENV=production
      - PORT=${PORT:-3000}
    # Optionally load env files for container runtime env
    env_file:
      - .env.production
      - .env
    restart: unless-stopped
    # Uncomment for stricter sandboxing; ensure the app doesn't need writes.
    # read_only: true
    # tmpfs:
    #   - /tmp
    # security_opt:
    #   - no-new-privileges:true
    # cap_drop:
    #   - ALL
